name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        go_version: [1.17.x]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash    
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v2
      - name: Prepare for xgo
        run: |
          pwd
          ls -al
          echo '${{ github.workspace }}'
          ls ${{ github.workspace }}
          #mkdir src
          #cp checkpath.go src
          printenv | sort
          #fix for xgo build
          #printf "module checkpath\n\ngo 1.17\n" >go.mod
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          prefix: checkpath
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: true
          ldflags: -s -w
          buildmode: default
        env:
          GOPATH: ${{ github.workspace }}          
      - name: Upload using GitHub cli
        run: |
          gh --version
          version="$(basename $GITHUB_REF)"
          echo $version
          gh release upload $version build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

