name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      matrix:
        go_version: [1.17.x]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: true
      - name: Run tests
        run: |
          go test
      - name: Build with xgo
        run: |
          pwd
          ls -al
          echo '${{ github.workspace }}'
          go version
          printenv | sort
          mkdir build && cd build
          docker pull karalabe/xgo-latest
          echo '------------------------'
          go get github.com/karalabe/xgo
          ls -al ~/go/bin/
          ~/go/bin/xgo -v -x -ldflags='-s -w' --targets='windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64' github.com/stochmal/checkpath-go
          cd .. && ls -al build
      - name: Upload using GitHub cli
        run: |
          gh --version
          version="$(basename $GITHUB_REF)"
          echo $version
          gh release upload $version build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

